
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2008-08-13
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SapService
{

  /// <summary>
  /// 
  /// </summary>
  [RfcStructure(AbapName ="RFC_DB_FLD" , Length = 103, Length2 = 206)]
  [Serializable]
  public class RFC_DB_FLD : SAPStructure
  {
   

    /// <summary>
    /// Field Name
    /// </summary>
 
    [RfcField(AbapName = "FIELDNAME", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Length2 = 60, Offset = 0, Offset2 = 0)]
    [XmlElement("FIELDNAME")]
    public string Fieldname
    { 
       get
       {
          return _Fieldname;
       }
       set
       {
          _Fieldname = value;
       }
    }
    private string _Fieldname;


    /// <summary>
    /// Offset of a field
    /// </summary>
 
    [RfcField(AbapName = "OFFSET", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 6, Length2 = 12, Offset = 30, Offset2 = 60)]
    [XmlElement("OFFSET")]
    public string Offset
    { 
       get
       {
          return _Offset;
       }
       set
       {
          _Offset = value;
       }
    }
    private string _Offset;


    /// <summary>
    /// Length (No. of Characters)
    /// </summary>
 
    [RfcField(AbapName = "LENGTH", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 6, Length2 = 12, Offset = 36, Offset2 = 72)]
    [XmlElement("LENGTH")]
    public string Length
    { 
       get
       {
          return _Length;
       }
       set
       {
          _Length = value;
       }
    }
    private string _Length;


    /// <summary>
    /// ABAP data type (C,D,N,...)
    /// </summary>
 
    [RfcField(AbapName = "TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Length2 = 2, Offset = 42, Offset2 = 84)]
    [XmlElement("TYPE")]
    public string Type
    { 
       get
       {
          return _Type;
       }
       set
       {
          _Type = value;
       }
    }
    private string _Type;


    /// <summary>
    /// Short Text Describing R/3 Repository Objects
    /// </summary>
 
    [RfcField(AbapName = "FIELDTEXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 60, Length2 = 120, Offset = 43, Offset2 = 86)]
    [XmlElement("FIELDTEXT")]
    public string Fieldtext
    { 
       get
       {
          return _Fieldtext;
       }
       set
       {
          _Fieldtext = value;
       }
    }
    private string _Fieldtext;

  }

}
