
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2008-08-13
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SapService
{

  /// <summary>
  /// 
  /// </summary>
  [RfcStructure(AbapName ="RFC_DB_OPT" , Length = 72, Length2 = 144)]
  [Serializable]
  public class RFC_DB_OPT : SAPStructure
  {
   

    /// <summary>
    /// Text line of a message
    /// </summary>
 
    [RfcField(AbapName = "TEXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 72, Length2 = 144, Offset = 0, Offset2 = 0)]
    [XmlElement("TEXT")]
    public string Text
    { 
       get
       {
          return _Text;
       }
       set
       {
          _Text = value;
       }
    }
    private string _Text;

  }

}
