
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2008-08-13
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SapService
{
  /// <summary>
  /// A typed collection of TAB512 elements.
  /// </summary>
  [Serializable]
  public class TAB512Table : SAPTable 
  {
  
    /// <summary>
    /// Returns the element type TAB512.
    /// </summary>
    /// <returns>The type TAB512.</returns>
    public override Type GetElementType() 
    {
        return (typeof(TAB512));
    }

    /// <summary>
    /// Creates an empty new row of type TAB512.
    /// </summary>
    /// <returns>The newTAB512.</returns>
    public override object CreateNewRow()
    { 
        return new TAB512();
    }
     
    /// <summary>
    /// The indexer of the collection.
    /// </summary>
    public TAB512 this[int index] 
    {
        get 
        {
            return ((TAB512)(List[index]));
        }
        set 
        {
            List[index] = value;
        }
    }
        
    /// <summary>
    /// Adds a TAB512 to the end of the collection.
    /// </summary>
    /// <param name="value">The TAB512 to be added to the end of the collection.</param>
    /// <returns>The index of the newTAB512.</returns>
    public int Add(TAB512 value) 
    {
        return List.Add(value);
    }
        
    /// <summary>
    /// Inserts a TAB512 into the collection at the specified index.
    /// </summary>
    /// <param name="index">The zero-based index at which value should be inserted.</param>
    /// <param name="value">The TAB512 to insert.</param>
    public void Insert(int index, TAB512 value) 
    {
        List.Insert(index, value);
    }
        
    /// <summary>
    /// Searches for the specified TAB512 and returnes the zero-based index of the first occurrence in the collection.
    /// </summary>
    /// <param name="value">The TAB512 to locate in the collection.</param>
    /// <returns>The index of the object found or -1.</returns>
    public int IndexOf(TAB512 value) 
    {
        return List.IndexOf(value);
    }
        
    /// <summary>
    /// Determines wheter an element is in the collection.
    /// </summary>
    /// <param name="value">The TAB512 to locate in the collection.</param>
    /// <returns>True if found; else false.</returns>
    public bool Contains(TAB512 value) 
    {
        return List.Contains(value);
    }
        
    /// <summary>
    /// Removes the first occurrence of the specified TAB512 from the collection.
    /// </summary>
    /// <param name="value">The TAB512 to remove from the collection.</param>
    public void Remove(TAB512 value) 
    {
        List.Remove(value);
    }

    /// <summary>
    /// Copies the contents of the TAB512Table to the specified one-dimensional array starting at the specified index in the target array.
    /// </summary>
    /// <param name="array">The one-dimensional destination array.</param>           
    /// <param name="index">The zero-based index in array at which copying begins.</param>           
    public void CopyTo(TAB512[] array, int index) 
    {
        List.CopyTo(array, index);
	}
  }
}
