
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2008-08-13
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SapService
{

  /// <summary>
  /// 
  /// </summary>
  [RfcStructure(AbapName ="ZSMM_RFC_PBF" , Length = 188, Length2 = 338)]
  [Serializable]
  public class ZSMM_RFC_PBF : SAPStructure
  {
   

    /// <summary>
    /// Item Number of Reservation / Dependent Requirements
    /// </summary>
 
    [RfcField(AbapName = "RSPOS", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 4, Length2 = 8, Offset = 0, Offset2 = 0)]
    [XmlElement("RSPOS")]
    public string Rspos
    { 
       get
       {
          return _Rspos;
       }
       set
       {
          _Rspos = value;
       }
    }
    private string _Rspos;


    /// <summary>
    /// Plant
    /// </summary>
 
    [RfcField(AbapName = "WERKS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 4, Offset2 = 8)]
    [XmlElement("WERKS")]
    public string Werks
    { 
       get
       {
          return _Werks;
       }
       set
       {
          _Werks = value;
       }
    }
    private string _Werks;


    /// <summary>
    /// Material Number
    /// </summary>
 
    [RfcField(AbapName = "MATNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Length2 = 36, Offset = 8, Offset2 = 16)]
    [XmlElement("MATNR")]
    public string Matnr
    { 
       get
       {
          return _Matnr;
       }
       set
       {
          _Matnr = value;
       }
    }
    private string _Matnr;


    /// <summary>
    /// Batch Number
    /// </summary>
 
    [RfcField(AbapName = "CHARG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 26, Offset2 = 52)]
    [XmlElement("CHARG")]
    public string Charg
    { 
       get
       {
          return _Charg;
       }
       set
       {
          _Charg = value;
       }
    }
    private string _Charg;


    /// <summary>
    /// Storage location
    /// </summary>
 
    [RfcField(AbapName = "LGORT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 36, Offset2 = 72)]
    [XmlElement("LGORT")]
    public string Lgort
    { 
       get
       {
          return _Lgort;
       }
       set
       {
          _Lgort = value;
       }
    }
    private string _Lgort;


    /// <summary>
    /// Receiving plant/issuing plant
    /// </summary>
 
    [RfcField(AbapName = "UMWRK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 40, Offset2 = 80)]
    [XmlElement("UMWRK")]
    public string Umwrk
    { 
       get
       {
          return _Umwrk;
       }
       set
       {
          _Umwrk = value;
       }
    }
    private string _Umwrk;


    /// <summary>
    /// Receiving/issuing storage location
    /// </summary>
 
    [RfcField(AbapName = "UMLGO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 44, Offset2 = 88)]
    [XmlElement("UMLGO")]
    public string Umlgo
    { 
       get
       {
          return _Umlgo;
       }
       set
       {
          _Umlgo = value;
       }
    }
    private string _Umlgo;


    /// <summary>
    /// Material description
    /// </summary>
 
    [RfcField(AbapName = "MAKTX", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 48, Offset2 = 96)]
    [XmlElement("MAKTX")]
    public string Maktx
    { 
       get
       {
          return _Maktx;
       }
       set
       {
          _Maktx = value;
       }
    }
    private string _Maktx;


    /// <summary>
    /// Unit of entry
    /// </summary>
 
    [RfcField(AbapName = "ERFME", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 88, Offset2 = 176)]
    [XmlElement("ERFME")]
    public string Erfme
    { 
       get
       {
          return _Erfme;
       }
       set
       {
          _Erfme = value;
       }
    }
    private string _Erfme;


    /// <summary>
    /// Quantity in unit of entry
    /// </summary>
 
    [RfcField(AbapName = "ERFMG", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 91, Offset2 = 182)]
    [XmlElement("ERFMG")]
    public Decimal Erfmg
    { 
       get
       {
          return _Erfmg;
       }
       set
       {
          _Erfmg = value;
       }
    }
    private Decimal _Erfmg;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "MENGW", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 98, Offset2 = 189)]
    [XmlElement("MENGW")]
    public Decimal Mengw
    { 
       get
       {
          return _Mengw;
       }
       set
       {
          _Mengw = value;
       }
    }
    private Decimal _Mengw;


    /// <summary>
    /// Valuated stock with unrestricted use
    /// </summary>
 
    [RfcField(AbapName = "CLABS", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 105, Offset2 = 196)]
    [XmlElement("CLABS")]
    public Decimal Clabs
    { 
       get
       {
          return _Clabs;
       }
       set
       {
          _Clabs = value;
       }
    }
    private Decimal _Clabs;


    /// <summary>
    /// Char 15
    /// </summary>
 
    [RfcField(AbapName = "BCT50", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 112, Offset2 = 204)]
    [XmlElement("BCT50")]
    public string Bct50
    { 
       get
       {
          return _Bct50;
       }
       set
       {
          _Bct50 = value;
       }
    }
    private string _Bct50;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "BCT51", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 127, Offset2 = 234)]
    [XmlElement("BCT51")]
    public Decimal Bct51
    { 
       get
       {
          return _Bct51;
       }
       set
       {
          _Bct51 = value;
       }
    }
    private Decimal _Bct51;


    /// <summary>
    /// Char 15
    /// </summary>
 
    [RfcField(AbapName = "BCT60", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 134, Offset2 = 242)]
    [XmlElement("BCT60")]
    public string Bct60
    { 
       get
       {
          return _Bct60;
       }
       set
       {
          _Bct60 = value;
       }
    }
    private string _Bct60;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "BCT61", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 149, Offset2 = 272)]
    [XmlElement("BCT61")]
    public Decimal Bct61
    { 
       get
       {
          return _Bct61;
       }
       set
       {
          _Bct61 = value;
       }
    }
    private Decimal _Bct61;


    /// <summary>
    /// Char 15
    /// </summary>
 
    [RfcField(AbapName = "BCT70", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 156, Offset2 = 280)]
    [XmlElement("BCT70")]
    public string Bct70
    { 
       get
       {
          return _Bct70;
       }
       set
       {
          _Bct70 = value;
       }
    }
    private string _Bct70;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "BCT71", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 171, Offset2 = 310)]
    [XmlElement("BCT71")]
    public Decimal Bct71
    { 
       get
       {
          return _Bct71;
       }
       set
       {
          _Bct71 = value;
       }
    }
    private Decimal _Bct71;


    /// <summary>
    /// Character Field Length = 10
    /// </summary>
 
    [RfcField(AbapName = "BCT10", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 178, Offset2 = 318)]
    [XmlElement("BCT10")]
    public string Bct10
    { 
       get
       {
          return _Bct10;
       }
       set
       {
          _Bct10 = value;
       }
    }
    private string _Bct10;

  }

}
