
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2008-08-13
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SapService
{

  /// <summary>
  /// 
  /// </summary>
  [RfcStructure(AbapName ="ZSMM_RFC_PBA" , Length = 171, Length2 = 300)]
  [Serializable]
  public class ZSMM_RFC_PBA : SAPStructure
  {
   

    /// <summary>
    /// Item Number of Reservation / Dependent Requirements
    /// </summary>
 
    [RfcField(AbapName = "RSPOS", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 4, Length2 = 8, Offset = 0, Offset2 = 0)]
    [XmlElement("RSPOS")]
    public string Rspos
    { 
       get
       {
          return _Rspos;
       }
       set
       {
          _Rspos = value;
       }
    }
    private string _Rspos;


    /// <summary>
    /// Storage location
    /// </summary>
 
    [RfcField(AbapName = "LGORT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 4, Offset2 = 8)]
    [XmlElement("LGORT")]
    public string Lgort
    { 
       get
       {
          return _Lgort;
       }
       set
       {
          _Lgort = value;
       }
    }
    private string _Lgort;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "MENGE", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 8, Offset2 = 16)]
    [XmlElement("MENGE")]
    public Decimal Menge
    { 
       get
       {
          return _Menge;
       }
       set
       {
          _Menge = value;
       }
    }
    private Decimal _Menge;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "REASON", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 4, Length2 = 8, Offset = 15, Offset2 = 24)]
    [XmlElement("REASON")]
    public string Reason
    { 
       get
       {
          return _Reason;
       }
       set
       {
          _Reason = value;
       }
    }
    private string _Reason;


    /// <summary>
    /// Char 15
    /// </summary>
 
    [RfcField(AbapName = "BCT50", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 19, Offset2 = 32)]
    [XmlElement("BCT50")]
    public string Bct50
    { 
       get
       {
          return _Bct50;
       }
       set
       {
          _Bct50 = value;
       }
    }
    private string _Bct50;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "BCT51", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 34, Offset2 = 62)]
    [XmlElement("BCT51")]
    public Decimal Bct51
    { 
       get
       {
          return _Bct51;
       }
       set
       {
          _Bct51 = value;
       }
    }
    private Decimal _Bct51;


    /// <summary>
    /// Char 15
    /// </summary>
 
    [RfcField(AbapName = "BCT60", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 41, Offset2 = 70)]
    [XmlElement("BCT60")]
    public string Bct60
    { 
       get
       {
          return _Bct60;
       }
       set
       {
          _Bct60 = value;
       }
    }
    private string _Bct60;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "BCT61", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 56, Offset2 = 100)]
    [XmlElement("BCT61")]
    public Decimal Bct61
    { 
       get
       {
          return _Bct61;
       }
       set
       {
          _Bct61 = value;
       }
    }
    private Decimal _Bct61;


    /// <summary>
    /// Char 15
    /// </summary>
 
    [RfcField(AbapName = "BCT70", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 63, Offset2 = 108)]
    [XmlElement("BCT70")]
    public string Bct70
    { 
       get
       {
          return _Bct70;
       }
       set
       {
          _Bct70 = value;
       }
    }
    private string _Bct70;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "BCT71", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 78, Offset2 = 138)]
    [XmlElement("BCT71")]
    public Decimal Bct71
    { 
       get
       {
          return _Bct71;
       }
       set
       {
          _Bct71 = value;
       }
    }
    private Decimal _Bct71;


    /// <summary>
    /// Character Field Length = 10
    /// </summary>
 
    [RfcField(AbapName = "BCT10", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 85, Offset2 = 146)]
    [XmlElement("BCT10")]
    public string Bct10
    { 
       get
       {
          return _Bct10;
       }
       set
       {
          _Bct10 = value;
       }
    }
    private string _Bct10;


    /// <summary>
    /// Char 15
    /// </summary>
 
    [RfcField(AbapName = "PCT50", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 95, Offset2 = 166)]
    [XmlElement("PCT50")]
    public string Pct50
    { 
       get
       {
          return _Pct50;
       }
       set
       {
          _Pct50 = value;
       }
    }
    private string _Pct50;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "PCT51", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 110, Offset2 = 196)]
    [XmlElement("PCT51")]
    public Decimal Pct51
    { 
       get
       {
          return _Pct51;
       }
       set
       {
          _Pct51 = value;
       }
    }
    private Decimal _Pct51;


    /// <summary>
    /// Char 15
    /// </summary>
 
    [RfcField(AbapName = "PCT60", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 117, Offset2 = 204)]
    [XmlElement("PCT60")]
    public string Pct60
    { 
       get
       {
          return _Pct60;
       }
       set
       {
          _Pct60 = value;
       }
    }
    private string _Pct60;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "PCT61", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 132, Offset2 = 234)]
    [XmlElement("PCT61")]
    public Decimal Pct61
    { 
       get
       {
          return _Pct61;
       }
       set
       {
          _Pct61 = value;
       }
    }
    private Decimal _Pct61;


    /// <summary>
    /// Char 15
    /// </summary>
 
    [RfcField(AbapName = "PCT70", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 139, Offset2 = 242)]
    [XmlElement("PCT70")]
    public string Pct70
    { 
       get
       {
          return _Pct70;
       }
       set
       {
          _Pct70 = value;
       }
    }
    private string _Pct70;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "PCT71", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 154, Offset2 = 272)]
    [XmlElement("PCT71")]
    public Decimal Pct71
    { 
       get
       {
          return _Pct71;
       }
       set
       {
          _Pct71 = value;
       }
    }
    private Decimal _Pct71;


    /// <summary>
    /// Character Field Length = 10
    /// </summary>
 
    [RfcField(AbapName = "PCT10", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 161, Offset2 = 280)]
    [XmlElement("PCT10")]
    public string Pct10
    { 
       get
       {
          return _Pct10;
       }
       set
       {
          _Pct10 = value;
       }
    }
    private string _Pct10;

  }

}
