
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2008-08-13
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SapService
{

  /// <summary>
  /// 
  /// </summary>
  [RfcStructure(AbapName ="ZSMM_RFC_REC" , Length = 182, Length2 = 342)]
  [Serializable]
  public class ZSMM_RFC_REC : SAPStructure
  {
   

    /// <summary>
    /// Item in Material Document
    /// </summary>
 
    [RfcField(AbapName = "ZEILE", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 4, Length2 = 8, Offset = 0, Offset2 = 0)]
    [XmlElement("ZEILE")]
    public string Zeile
    { 
       get
       {
          return _Zeile;
       }
       set
       {
          _Zeile = value;
       }
    }
    private string _Zeile;


    /// <summary>
    /// Material Number
    /// </summary>
 
    [RfcField(AbapName = "MATNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Length2 = 36, Offset = 4, Offset2 = 8)]
    [XmlElement("MATNR")]
    public string Matnr
    { 
       get
       {
          return _Matnr;
       }
       set
       {
          _Matnr = value;
       }
    }
    private string _Matnr;


    /// <summary>
    /// Batch Number
    /// </summary>
 
    [RfcField(AbapName = "CHARG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 22, Offset2 = 44)]
    [XmlElement("CHARG")]
    public string Charg
    { 
       get
       {
          return _Charg;
       }
       set
       {
          _Charg = value;
       }
    }
    private string _Charg;


    /// <summary>
    /// Company Code
    /// </summary>
 
    [RfcField(AbapName = "BUKRS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 32, Offset2 = 64)]
    [XmlElement("BUKRS")]
    public string Bukrs
    { 
       get
       {
          return _Bukrs;
       }
       set
       {
          _Bukrs = value;
       }
    }
    private string _Bukrs;


    /// <summary>
    /// Storage location
    /// </summary>
 
    [RfcField(AbapName = "LGORT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 36, Offset2 = 72)]
    [XmlElement("LGORT")]
    public string Lgort
    { 
       get
       {
          return _Lgort;
       }
       set
       {
          _Lgort = value;
       }
    }
    private string _Lgort;


    /// <summary>
    /// Material description
    /// </summary>
 
    [RfcField(AbapName = "MAKTX", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 40, Offset2 = 80)]
    [XmlElement("MAKTX")]
    public string Maktx
    { 
       get
       {
          return _Maktx;
       }
       set
       {
          _Maktx = value;
       }
    }
    private string _Maktx;


    /// <summary>
    /// Base Unit of Measure
    /// </summary>
 
    [RfcField(AbapName = "MEINS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 80, Offset2 = 160)]
    [XmlElement("MEINS")]
    public string Meins
    { 
       get
       {
          return _Meins;
       }
       set
       {
          _Meins = value;
       }
    }
    private string _Meins;


    /// <summary>
    /// Net weight
    /// </summary>
 
    [RfcField(AbapName = "NTGEW", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 83, Offset2 = 166)]
    [XmlElement("NTGEW")]
    public Decimal Ntgew
    { 
       get
       {
          return _Ntgew;
       }
       set
       {
          _Ntgew = value;
       }
    }
    private Decimal _Ntgew;


    /// <summary>
    /// Net value in document currency
    /// </summary>
 
    [RfcField(AbapName = "NETWR", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Length2 = 8, Decimals = 2, Offset = 90, Offset2 = 173)]
    [XmlElement("NETWR")]
    public Decimal Netwr
    { 
       get
       {
          return _Netwr;
       }
       set
       {
          _Netwr = value;
       }
    }
    private Decimal _Netwr;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "MENGE", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 98, Offset2 = 181)]
    [XmlElement("MENGE")]
    public Decimal Menge
    { 
       get
       {
          return _Menge;
       }
       set
       {
          _Menge = value;
       }
    }
    private Decimal _Menge;


    /// <summary>
    /// Purchasing Organization
    /// </summary>
 
    [RfcField(AbapName = "EKORG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 105, Offset2 = 188)]
    [XmlElement("EKORG")]
    public string Ekorg
    { 
       get
       {
          return _Ekorg;
       }
       set
       {
          _Ekorg = value;
       }
    }
    private string _Ekorg;


    /// <summary>
    /// Purchasing group
    /// </summary>
 
    [RfcField(AbapName = "EKGRP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 109, Offset2 = 196)]
    [XmlElement("EKGRP")]
    public string Ekgrp
    { 
       get
       {
          return _Ekgrp;
       }
       set
       {
          _Ekgrp = value;
       }
    }
    private string _Ekgrp;


    /// <summary>
    /// Character field, length 70
    /// </summary>
 
    [RfcField(AbapName = "TEXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 70, Length2 = 140, Offset = 112, Offset2 = 202)]
    [XmlElement("TEXT")]
    public string Text
    { 
       get
       {
          return _Text;
       }
       set
       {
          _Text = value;
       }
    }
    private string _Text;

  }

}
