
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2008-08-13
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SapService
{

  /// <summary>
  /// 
  /// </summary>
  [RfcStructure(AbapName ="ZSMM_RFC_RCTP" , Length = 14, Length2 = 28)]
  [Serializable]
  public class ZSMM_RFC_RCTP : SAPStructure
  {
   

    /// <summary>
    /// Item in Material Document
    /// </summary>
 
    [RfcField(AbapName = "ZEILE", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 4, Length2 = 8, Offset = 0, Offset2 = 0)]
    [XmlElement("ZEILE")]
    public string Zeile
    { 
       get
       {
          return _Zeile;
       }
       set
       {
          _Zeile = value;
       }
    }
    private string _Zeile;


    /// <summary>
    /// Batch Number
    /// </summary>
 
    [RfcField(AbapName = "CHARG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 4, Offset2 = 8)]
    [XmlElement("CHARG")]
    public string Charg
    { 
       get
       {
          return _Charg;
       }
       set
       {
          _Charg = value;
       }
    }
    private string _Charg;

  }

}
