
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2008-08-13
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.ComponentModel;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SapService
{

  /// <summary>
  /// Client SAP proxy class
  /// </summary>
  [WebServiceBinding(Name="dummy.Binding", Namespace="urn:sap-com:document:sap:rfc:functions")]
  [Serializable]
  public class SAPJob : SAPClient
  {
    /// <summary>
    /// Initializes a new SAPJob.
    /// </summary>
    public SAPJob(){}

    /// <summary>
    /// Initializes a new SAPJob with a new connection based on the specified connection string.
    /// </summary>
    /// <param name="connectionString">A connection string (e.g. RFC or URL) specifying the system where the proxy should connect to.</param>
    public SAPJob(string connectionString) : base(connectionString){}

    /// <summary>
    /// Initializes a new SAPJob instance and adds it to the given container.
    /// This allows automated connection mananged by VS component designer:
    /// If container is disposed, it will also dispose this SAPClient instance,
    /// which will dispose a contained connection if needed.
    /// </summary>
    /// <param name="container"<The container where the new SAPClient instance is to be added.>/param<
    public SAPJob(System.ComponentModel.IContainer container) : base(container) {}    
  
    /// <summary>
    /// Exception constant for ABAP-Exception DATA_BUFFER_EXCEEDED
    /// </summary>
    public const string Data_Buffer_Exceeded = "DATA_BUFFER_EXCEEDED";
   
    /// <summary>
    /// Exception constant for ABAP-Exception FIELD_NOT_VALID
    /// </summary>
    public const string Field_Not_Valid = "FIELD_NOT_VALID";
   
    /// <summary>
    /// Exception constant for ABAP-Exception NOT_AUTHORIZED
    /// </summary>
    public const string Not_Authorized = "NOT_AUTHORIZED";
   
    /// <summary>
    /// Exception constant for ABAP-Exception OPTION_NOT_VALID
    /// </summary>
    public const string Option_Not_Valid = "OPTION_NOT_VALID";
   
    /// <summary>
    /// Exception constant for ABAP-Exception TABLE_NOT_AVAILABLE
    /// </summary>
    public const string Table_Not_Available = "TABLE_NOT_AVAILABLE";
   
    /// <summary>
    /// Exception constant for ABAP-Exception TABLE_WITHOUT_DATA
    /// </summary>
    public const string Table_Without_Data = "TABLE_WITHOUT_DATA";
   
    /// <summary>
    /// Remote Function Module RFC_READ_TABLE.  
    /// External access to R/3 tables via RFC
    /// </summary>
    /// <param name="Delimiter">Sign for indicating field limits in DATA</param>
    /// <param name="No_Data">If <> SPACE, only FIELDS is filled</param>
    /// <param name="Query_Table">Table read</param>
    /// <param name="Rowcount">If <> SPACE, only FIELDS is filled</param>
    /// <param name="Rowskips">If <> SPACE, only FIELDS is filled</param>
    /// <param name="Data">Data read (out)</param>
    /// <param name="Fields">Names (in) and structure (out) of fields read</param>
    /// <param name="Options">Selection entries, "WHERE clauses" (in)</param> 
    /// <exception cref="Data_Buffer_Exceeded"/> 
    /// <exception cref="Field_Not_Valid"/> 
    /// <exception cref="Not_Authorized"/> 
    /// <exception cref="Option_Not_Valid"/> 
    /// <exception cref="Table_Not_Available"/> 
    /// <exception cref="Table_Without_Data"/>
    [RfcMethod(AbapName = "RFC_READ_TABLE")]
    [SoapDocumentMethodAttribute("http://tempuri.org/RFC_READ_TABLE",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "RFC_READ_TABLE",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "RFC_READ_TABLE.Response")]
    public virtual void Rfc_Read_Table (

     [RfcParameter(AbapName = "DELIMITER",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 1, Length2 = 2)]
     [XmlElement("DELIMITER", IsNullable=false, Namespace="")]
     string Delimiter,
     [RfcParameter(AbapName = "NO_DATA",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 1, Length2 = 2)]
     [XmlElement("NO_--5fDATA", IsNullable=false, Namespace="")]
     string No_Data,
     [RfcParameter(AbapName = "QUERY_TABLE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 30, Length2 = 60)]
     [XmlElement("QUERY_--5fTABLE", IsNullable=false, Namespace="")]
     string Query_Table,
     [RfcParameter(AbapName = "ROWCOUNT",RfcType=RFCTYPE.RFCTYPE_INT, Optional = true, Direction = RFCINOUT.IN, Length = 4, Length2 = 4)]
     [XmlElement("ROWCOUNT", IsNullable=false, Namespace="")]
     int Rowcount,
     [RfcParameter(AbapName = "ROWSKIPS",RfcType=RFCTYPE.RFCTYPE_INT, Optional = true, Direction = RFCINOUT.IN, Length = 4, Length2 = 4)]
     [XmlElement("ROWSKIPS", IsNullable=false, Namespace="")]
     int Rowskips,
     [RfcParameter(AbapName = "DATA",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("DATA", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref TAB512Table Data,
     [RfcParameter(AbapName = "FIELDS",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("FIELDS", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref RFC_DB_FLDTable Fields,
     [RfcParameter(AbapName = "OPTIONS",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("OPTIONS", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref RFC_DB_OPTTable Options)
    {
        object[]results = null;
        results = this.SAPInvoke("Rfc_Read_Table",new object[] {
                            Delimiter,No_Data,Query_Table,Rowcount,Rowskips,Data,Fields,Options });
        Data = (TAB512Table) results[0];
        Fields = (RFC_DB_FLDTable) results[1];
        Options = (RFC_DB_OPTTable) results[2];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_PO_UPLOAD.  
    /// 
    /// </summary>
    /// <param name="Mblnr"></param>
    /// <param name="Mjahr"></param>
    /// <param name="Returncode"></param>
    /// <param name="Bct10"></param>
    /// <param name="Budat"></param>
    /// <param name="Ebeln"></param>
    /// <param name="Pt_Kc"></param>
    /// <param name="Return"></param>
    [RfcMethod(AbapName = "ZMM_RFC_PO_UPLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_PO_UPLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_PO_UPLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_PO_UPLOAD.Response")]
    public virtual void Zmm_Rfc_Po_Upload (

     [RfcParameter(AbapName = "BCT10",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("BCT10", IsNullable=false, Namespace="")]
     string Bct10,
     [RfcParameter(AbapName = "BUDAT",RfcType=RFCTYPE.RFCTYPE_DATE, Optional = true, Direction = RFCINOUT.IN, Length = 8, Length2 = 16)]
     [XmlElement("BUDAT", IsNullable=false, Namespace="")]
     string Budat,
     [RfcParameter(AbapName = "EBELN",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("EBELN", IsNullable=false, Namespace="")]
     string Ebeln,
     [RfcParameter(AbapName = "MBLNR",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 10, Length2 = 20)]
     [XmlElement("MBLNR", IsNullable=false, Namespace="")]
     out string Mblnr,
     [RfcParameter(AbapName = "MJAHR",RfcType=RFCTYPE.RFCTYPE_NUM, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 8)]
     [XmlElement("MJAHR", IsNullable=false, Namespace="")]
     out string Mjahr,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "PT_KC",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("PT_--5fKC", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_POUPTable Pt_Kc,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Po_Upload",new object[] {
                            Bct10,Budat,Ebeln,Pt_Kc,Return });
        Mblnr = (string) results[0];
        Mjahr = (string) results[1];
        Returncode = (string) results[2];
        Pt_Kc = (ZSMM_RFC_POUPTable) results[3];
        Return = (BAPIRET2Table) results[4];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_PO_DOWNLOAD.  
    /// 
    /// </summary>
    /// <param name="Ekgrp"></param>
    /// <param name="Ekorg"></param>
    /// <param name="Ernam"></param>
    /// <param name="Lifnr"></param>
    /// <param name="Name1"></param>
    /// <param name="Name_Textc"></param>
    /// <param name="Returncode"></param>
    /// <param name="Bwart"></param>
    /// <param name="Po_Num"></param>
    /// <param name="Po_Detail"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_PO_DOWNLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_PO_DOWNLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_PO_DOWNLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_PO_DOWNLOAD.Response")]
    public virtual void Zmm_Rfc_Po_Download (

     [RfcParameter(AbapName = "BWART",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 3, Length2 = 6)]
     [XmlElement("BWART", IsNullable=false, Namespace="")]
     string Bwart,
     [RfcParameter(AbapName = "PO_NUM",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("PO_--5fNUM", IsNullable=false, Namespace="")]
     string Po_Num,
     [RfcParameter(AbapName = "EKGRP",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 3, Length2 = 6)]
     [XmlElement("EKGRP", IsNullable=false, Namespace="")]
     out string Ekgrp,
     [RfcParameter(AbapName = "EKORG",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 8)]
     [XmlElement("EKORG", IsNullable=false, Namespace="")]
     out string Ekorg,
     [RfcParameter(AbapName = "ERNAM",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 12, Length2 = 24)]
     [XmlElement("ERNAM", IsNullable=false, Namespace="")]
     out string Ernam,
     [RfcParameter(AbapName = "LIFNR",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 10, Length2 = 20)]
     [XmlElement("LIFNR", IsNullable=false, Namespace="")]
     out string Lifnr,
     [RfcParameter(AbapName = "NAME_TEXTC",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 80, Length2 = 160)]
     [XmlElement("NAME_--5fTEXTC", IsNullable=false, Namespace="")]
     out string Name_Textc,
     [RfcParameter(AbapName = "NAME1",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 35, Length2 = 70)]
     [XmlElement("NAME1", IsNullable=false, Namespace="")]
     out string Name1,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "PO_DETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("PO_--5fDETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_PODTable Po_Detail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Po_Download",new object[] {
                            Bwart,Po_Num,Po_Detail,Return0 });
        Ekgrp = (string) results[0];
        Ekorg = (string) results[1];
        Ernam = (string) results[2];
        Lifnr = (string) results[3];
        Name_Textc = (string) results[4];
        Name1 = (string) results[5];
        Returncode = (string) results[6];
        Po_Detail = (ZSMM_RFC_PODTable) results[7];
        Return0 = (BAPIRET2Table) results[8];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_INBOUND_UD_LOAD.  
    /// 
    /// </summary>
    /// <param name="Returncode"></param>
    /// <param name="Ptype"></param>
    /// <param name="Pt_Inbound"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_INBOUND_UD_LOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_INBOUND_UD_LOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_INBOUND_UD_LOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_INBOUND_UD_LOAD.Response")]
    public virtual void Zmm_Rfc_Inbound_Ud_Load (

     [RfcParameter(AbapName = "PTYPE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 1, Length2 = 2)]
     [XmlElement("PTYPE", IsNullable=false, Namespace="")]
     string Ptype,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "PT_INBOUND",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("PT_--5fINBOUND", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_INBOUNDTable Pt_Inbound,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Inbound_Ud_Load",new object[] {
                            Ptype,Pt_Inbound,Return0 });
        Returncode = (string) results[0];
        Pt_Inbound = (ZSMM_RFC_INBOUNDTable) results[1];
        Return0 = (BAPIRET2Table) results[2];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_RECEIVE_DOWNLOAD.  
    /// 
    /// </summary>
    /// <param name="Ekgrp"></param>
    /// <param name="Ekorg"></param>
    /// <param name="Ernam"></param>
    /// <param name="Lifnr"></param>
    /// <param name="Name1"></param>
    /// <param name="Name_Textc"></param>
    /// <param name="Returncode"></param>
    /// <param name="Bwart"></param>
    /// <param name="Po_Num"></param>
    /// <param name="Po_Detail"></param>
    /// <param name="Return"></param>
    [RfcMethod(AbapName = "ZMM_RFC_RECEIVE_DOWNLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_RECEIVE_DOWNLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_RECEIVE_DOWNLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_RECEIVE_DOWNLOAD.Response")]
    public virtual void Zmm_Rfc_Receive_Download (

     [RfcParameter(AbapName = "BWART",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 3, Length2 = 6)]
     [XmlElement("BWART", IsNullable=false, Namespace="")]
     string Bwart,
     [RfcParameter(AbapName = "PO_NUM",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("PO_--5fNUM", IsNullable=false, Namespace="")]
     string Po_Num,
     [RfcParameter(AbapName = "EKGRP",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 3, Length2 = 6)]
     [XmlElement("EKGRP", IsNullable=false, Namespace="")]
     out string Ekgrp,
     [RfcParameter(AbapName = "EKORG",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 8)]
     [XmlElement("EKORG", IsNullable=false, Namespace="")]
     out string Ekorg,
     [RfcParameter(AbapName = "ERNAM",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 12, Length2 = 24)]
     [XmlElement("ERNAM", IsNullable=false, Namespace="")]
     out string Ernam,
     [RfcParameter(AbapName = "LIFNR",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 10, Length2 = 20)]
     [XmlElement("LIFNR", IsNullable=false, Namespace="")]
     out string Lifnr,
     [RfcParameter(AbapName = "NAME_TEXTC",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 80, Length2 = 160)]
     [XmlElement("NAME_--5fTEXTC", IsNullable=false, Namespace="")]
     out string Name_Textc,
     [RfcParameter(AbapName = "NAME1",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 35, Length2 = 70)]
     [XmlElement("NAME1", IsNullable=false, Namespace="")]
     out string Name1,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "PO_DETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("PO_--5fDETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_PDZTable Po_Detail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Receive_Download",new object[] {
                            Bwart,Po_Num,Po_Detail,Return });
        Ekgrp = (string) results[0];
        Ekorg = (string) results[1];
        Ernam = (string) results[2];
        Lifnr = (string) results[3];
        Name_Textc = (string) results[4];
        Name1 = (string) results[5];
        Returncode = (string) results[6];
        Po_Detail = (ZSMM_RFC_PDZTable) results[7];
        Return = (BAPIRET2Table) results[8];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_RECEIVE_UPLOAD.  
    /// 
    /// </summary>
    /// <param name="Mblnr"></param>
    /// <param name="Mjahr"></param>
    /// <param name="Returncode"></param>
    /// <param name="Bct10"></param>
    /// <param name="Budat"></param>
    /// <param name="Bwart"></param>
    /// <param name="Ebeln"></param>
    /// <param name="Pt_Kc"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_RECEIVE_UPLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_RECEIVE_UPLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_RECEIVE_UPLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_RECEIVE_UPLOAD.Response")]
    public virtual void Zmm_Rfc_Receive_Upload (

     [RfcParameter(AbapName = "BCT10",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("BCT10", IsNullable=false, Namespace="")]
     string Bct10,
     [RfcParameter(AbapName = "BUDAT",RfcType=RFCTYPE.RFCTYPE_DATE, Optional = true, Direction = RFCINOUT.IN, Length = 8, Length2 = 16)]
     [XmlElement("BUDAT", IsNullable=false, Namespace="")]
     string Budat,
     [RfcParameter(AbapName = "BWART",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 3, Length2 = 6)]
     [XmlElement("BWART", IsNullable=false, Namespace="")]
     string Bwart,
     [RfcParameter(AbapName = "EBELN",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("EBELN", IsNullable=false, Namespace="")]
     string Ebeln,
     [RfcParameter(AbapName = "MBLNR",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 10, Length2 = 20)]
     [XmlElement("MBLNR", IsNullable=false, Namespace="")]
     out string Mblnr,
     [RfcParameter(AbapName = "MJAHR",RfcType=RFCTYPE.RFCTYPE_NUM, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 8)]
     [XmlElement("MJAHR", IsNullable=false, Namespace="")]
     out string Mjahr,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "PT_KC",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("PT_--5fKC", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_RCUPTable Pt_Kc,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Receive_Upload",new object[] {
                            Bct10,Budat,Bwart,Ebeln,Pt_Kc,Return0 });
        Mblnr = (string) results[0];
        Mjahr = (string) results[1];
        Returncode = (string) results[2];
        Pt_Kc = (ZSMM_RFC_RCUPTable) results[3];
        Return0 = (BAPIRET2Table) results[4];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_DBG_DOWNLOAD.  
    /// 
    /// </summary>
    /// <param name="Ekgrp"></param>
    /// <param name="Ekorg"></param>
    /// <param name="Ernam"></param>
    /// <param name="Name1"></param>
    /// <param name="Name_Textc"></param>
    /// <param name="Reswk"></param>
    /// <param name="Returncode"></param>
    /// <param name="Po_Num"></param>
    /// <param name="Po_Detail"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_DBG_DOWNLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_DBG_DOWNLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_DBG_DOWNLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_DBG_DOWNLOAD.Response")]
    public virtual void Zmm_Rfc_Dbg_Download (

     [RfcParameter(AbapName = "PO_NUM",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("PO_--5fNUM", IsNullable=false, Namespace="")]
     string Po_Num,
     [RfcParameter(AbapName = "EKGRP",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 3, Length2 = 6)]
     [XmlElement("EKGRP", IsNullable=false, Namespace="")]
     out string Ekgrp,
     [RfcParameter(AbapName = "EKORG",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 8)]
     [XmlElement("EKORG", IsNullable=false, Namespace="")]
     out string Ekorg,
     [RfcParameter(AbapName = "ERNAM",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 12, Length2 = 24)]
     [XmlElement("ERNAM", IsNullable=false, Namespace="")]
     out string Ernam,
     [RfcParameter(AbapName = "NAME_TEXTC",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 80, Length2 = 160)]
     [XmlElement("NAME_--5fTEXTC", IsNullable=false, Namespace="")]
     out string Name_Textc,
     [RfcParameter(AbapName = "NAME1",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 30, Length2 = 60)]
     [XmlElement("NAME1", IsNullable=false, Namespace="")]
     out string Name1,
     [RfcParameter(AbapName = "RESWK",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 8)]
     [XmlElement("RESWK", IsNullable=false, Namespace="")]
     out string Reswk,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "PO_DETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("PO_--5fDETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_POBTable Po_Detail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Dbg_Download",new object[] {
                            Po_Num,Po_Detail,Return0 });
        Ekgrp = (string) results[0];
        Ekorg = (string) results[1];
        Ernam = (string) results[2];
        Name_Textc = (string) results[3];
        Name1 = (string) results[4];
        Reswk = (string) results[5];
        Returncode = (string) results[6];
        Po_Detail = (ZSMM_RFC_POBTable) results[7];
        Return0 = (BAPIRET2Table) results[8];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_LYCK_DOWNLOAD.  
    /// 
    /// </summary>
    /// <param name="Name1"></param>
    /// <param name="Reswk"></param>
    /// <param name="Returncode"></param>
    /// <param name="Po_Num"></param>
    /// <param name="Po_Detail"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_LYCK_DOWNLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_LYCK_DOWNLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_LYCK_DOWNLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_LYCK_DOWNLOAD.Response")]
    public virtual void Zmm_Rfc_Lyck_Download (

     [RfcParameter(AbapName = "PO_NUM",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("PO_--5fNUM", IsNullable=false, Namespace="")]
     string Po_Num,
     [RfcParameter(AbapName = "NAME1",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 30, Length2 = 60)]
     [XmlElement("NAME1", IsNullable=false, Namespace="")]
     out string Name1,
     [RfcParameter(AbapName = "RESWK",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 8)]
     [XmlElement("RESWK", IsNullable=false, Namespace="")]
     out string Reswk,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "PO_DETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("PO_--5fDETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_POSTable Po_Detail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Lyck_Download",new object[] {
                            Po_Num,Po_Detail,Return0 });
        Name1 = (string) results[0];
        Reswk = (string) results[1];
        Returncode = (string) results[2];
        Po_Detail = (ZSMM_RFC_POSTable) results[3];
        Return0 = (BAPIRET2Table) results[4];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_HWYD_DOWNLOAD.  
    /// 
    /// </summary>
    /// <param name="Returncode"></param>
    /// <param name="G_Detail"></param>
    /// <param name="P_Getail"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_HWYD_DOWNLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_HWYD_DOWNLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_HWYD_DOWNLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_HWYD_DOWNLOAD.Response")]
    public virtual void Zmm_Rfc_Hwyd_Download (

     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "G_DETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("G_--5fDETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_POTTable G_Detail,
     [RfcParameter(AbapName = "P_GETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("P_--5fGETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_POMTable P_Getail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Hwyd_Download",new object[] {
                            G_Detail,P_Getail,Return0 });
        Returncode = (string) results[0];
        G_Detail = (ZSMM_RFC_POTTable) results[1];
        P_Getail = (ZSMM_RFC_POMTable) results[2];
        Return0 = (BAPIRET2Table) results[3];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_HWYD_UPLOAD.  
    /// 
    /// </summary>
    /// <param name="Returncode"></param>
    /// <param name="G_Detail"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_HWYD_UPLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_HWYD_UPLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_HWYD_UPLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_HWYD_UPLOAD.Response")]
    public virtual void Zmm_Rfc_Hwyd_Upload (

     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "G_DETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("G_--5fDETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_POXTable G_Detail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Hwyd_Upload",new object[] {
                            G_Detail,Return0 });
        Returncode = (string) results[0];
        G_Detail = (ZSMM_RFC_POXTable) results[1];
        Return0 = (BAPIRET2Table) results[2];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_LYCK_UPLOAD.  
    /// 
    /// </summary>
    /// <param name="Mblnr"></param>
    /// <param name="Returncode"></param>
    /// <param name="Aedat"></param>
    /// <param name="Bct10"></param>
    /// <param name="Bwart"></param>
    /// <param name="Ebeln"></param>
    /// <param name="Werks"></param>
    /// <param name="P_Getail"></param>
    /// <param name="Return"></param>
    [RfcMethod(AbapName = "ZMM_RFC_LYCK_UPLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_LYCK_UPLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_LYCK_UPLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_LYCK_UPLOAD.Response")]
    public virtual void Zmm_Rfc_Lyck_Upload (

     [RfcParameter(AbapName = "AEDAT",RfcType=RFCTYPE.RFCTYPE_DATE, Optional = false, Direction = RFCINOUT.IN, Length = 8, Length2 = 16)]
     [XmlElement("AEDAT", IsNullable=false, Namespace="")]
     string Aedat,
     [RfcParameter(AbapName = "BCT10",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("BCT10", IsNullable=false, Namespace="")]
     string Bct10,
     [RfcParameter(AbapName = "BWART",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 3, Length2 = 6)]
     [XmlElement("BWART", IsNullable=false, Namespace="")]
     string Bwart,
     [RfcParameter(AbapName = "EBELN",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("EBELN", IsNullable=false, Namespace="")]
     string Ebeln,
     [RfcParameter(AbapName = "WERKS",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 4, Length2 = 8)]
     [XmlElement("WERKS", IsNullable=false, Namespace="")]
     string Werks,
     [RfcParameter(AbapName = "MBLNR",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 10, Length2 = 20)]
     [XmlElement("MBLNR", IsNullable=false, Namespace="")]
     out string Mblnr,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "P_GETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("P_--5fGETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_PABTable P_Getail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Lyck_Upload",new object[] {
                            Aedat,Bct10,Bwart,Ebeln,Werks,P_Getail,Return });
        Mblnr = (string) results[0];
        Returncode = (string) results[1];
        P_Getail = (ZSMM_RFC_PABTable) results[2];
        Return = (BAPIRET2Table) results[3];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_BF_DOWNLOAD.  
    /// 
    /// </summary>
    /// <param name="Returncode"></param>
    /// <param name="Rsnum"></param>
    /// <param name="P_Detail"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_BF_DOWNLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_BF_DOWNLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_BF_DOWNLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_BF_DOWNLOAD.Response")]
    public virtual void Zmm_Rfc_Bf_Download (

     [RfcParameter(AbapName = "RSNUM",RfcType=RFCTYPE.RFCTYPE_NUM, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("RSNUM", IsNullable=false, Namespace="")]
     string Rsnum,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "P_DETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("P_--5fDETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_PBFTable P_Detail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Bf_Download",new object[] {
                            Rsnum,P_Detail,Return0 });
        Returncode = (string) results[0];
        P_Detail = (ZSMM_RFC_PBFTable) results[1];
        Return0 = (BAPIRET2Table) results[2];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_PDSM_UPLOAD.  
    /// 
    /// </summary>
    /// <param name="Returncode"></param>
    /// <param name="Iblnr"></param>
    /// <param name="Werks"></param>
    /// <param name="Zldat"></param>
    /// <param name="Zpdstu"></param>
    /// <param name="P_Getail"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_PDSM_UPLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_PDSM_UPLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_PDSM_UPLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_PDSM_UPLOAD.Response")]
    public virtual void Zmm_Rfc_Pdsm_Upload (

     [RfcParameter(AbapName = "IBLNR",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("IBLNR", IsNullable=false, Namespace="")]
     string Iblnr,
     [RfcParameter(AbapName = "WERKS",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 4, Length2 = 8)]
     [XmlElement("WERKS", IsNullable=false, Namespace="")]
     string Werks,
     [RfcParameter(AbapName = "ZLDAT",RfcType=RFCTYPE.RFCTYPE_DATE, Optional = false, Direction = RFCINOUT.IN, Length = 8, Length2 = 16)]
     [XmlElement("ZLDAT", IsNullable=false, Namespace="")]
     string Zldat,
     [RfcParameter(AbapName = "ZPDSTU",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 2, Length2 = 4)]
     [XmlElement("ZPDSTU", IsNullable=false, Namespace="")]
     string Zpdstu,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "P_GETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("P_--5fGETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_PDSZTable P_Getail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Pdsm_Upload",new object[] {
                            Iblnr,Werks,Zldat,Zpdstu,P_Getail,Return0 });
        Returncode = (string) results[0];
        P_Getail = (ZSMM_RFC_PDSZTable) results[1];
        Return0 = (BAPIRET2Table) results[2];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_HWCX_DWNLOAD.  
    /// 
    /// </summary>
    /// <param name="Returncode"></param>
    /// <param name="P_Baogy"></param>
    /// <param name="P_Huowh"></param>
    /// <param name="P_Lgort"></param>
    /// <param name="P_Werks"></param>
    /// <param name="It_Output"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_HWCX_DWNLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_HWCX_DWNLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_HWCX_DWNLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_HWCX_DWNLOAD.Response")]
    public virtual void Zmm_Rfc_Hwcx_Dwnload (

     [RfcParameter(AbapName = "P_BAOGY",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("P_--5fBAOGY", IsNullable=false, Namespace="")]
     string P_Baogy,
     [RfcParameter(AbapName = "P_HUOWH",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 15, Length2 = 30)]
     [XmlElement("P_--5fHUOWH", IsNullable=false, Namespace="")]
     string P_Huowh,
     [RfcParameter(AbapName = "P_LGORT",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 4, Length2 = 8)]
     [XmlElement("P_--5fLGORT", IsNullable=false, Namespace="")]
     string P_Lgort,
     [RfcParameter(AbapName = "P_WERKS",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 4, Length2 = 8)]
     [XmlElement("P_--5fWERKS", IsNullable=false, Namespace="")]
     string P_Werks,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "IT_OUTPUT",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("IT_--5fOUTPUT", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_HUOWCXTable It_Output,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Hwcx_Dwnload",new object[] {
                            P_Baogy,P_Huowh,P_Lgort,P_Werks,It_Output,Return0 });
        Returncode = (string) results[0];
        It_Output = (ZSMM_RFC_HUOWCXTable) results[1];
        Return0 = (BAPIRET2Table) results[2];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_POTH_DOWNLOAD.  
    /// 
    /// </summary>
    /// <param name="Ekgrp"></param>
    /// <param name="Ekorg"></param>
    /// <param name="Ernam"></param>
    /// <param name="Lifnr"></param>
    /// <param name="Name1"></param>
    /// <param name="Name_Textc"></param>
    /// <param name="Returncode"></param>
    /// <param name="Po_Num"></param>
    /// <param name="Po_Detail"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_POTH_DOWNLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_POTH_DOWNLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_POTH_DOWNLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_POTH_DOWNLOAD.Response")]
    public virtual void Zmm_Rfc_Poth_Download (

     [RfcParameter(AbapName = "PO_NUM",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("PO_--5fNUM", IsNullable=false, Namespace="")]
     string Po_Num,
     [RfcParameter(AbapName = "EKGRP",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 3, Length2 = 6)]
     [XmlElement("EKGRP", IsNullable=false, Namespace="")]
     out string Ekgrp,
     [RfcParameter(AbapName = "EKORG",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 8)]
     [XmlElement("EKORG", IsNullable=false, Namespace="")]
     out string Ekorg,
     [RfcParameter(AbapName = "ERNAM",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 12, Length2 = 24)]
     [XmlElement("ERNAM", IsNullable=false, Namespace="")]
     out string Ernam,
     [RfcParameter(AbapName = "LIFNR",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 10, Length2 = 20)]
     [XmlElement("LIFNR", IsNullable=false, Namespace="")]
     out string Lifnr,
     [RfcParameter(AbapName = "NAME_TEXTC",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 80, Length2 = 160)]
     [XmlElement("NAME_--5fTEXTC", IsNullable=false, Namespace="")]
     out string Name_Textc,
     [RfcParameter(AbapName = "NAME1",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 35, Length2 = 70)]
     [XmlElement("NAME1", IsNullable=false, Namespace="")]
     out string Name1,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "PO_DETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("PO_--5fDETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_POHTable Po_Detail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Poth_Download",new object[] {
                            Po_Num,Po_Detail,Return0 });
        Ekgrp = (string) results[0];
        Ekorg = (string) results[1];
        Ernam = (string) results[2];
        Lifnr = (string) results[3];
        Name_Textc = (string) results[4];
        Name1 = (string) results[5];
        Returncode = (string) results[6];
        Po_Detail = (ZSMM_RFC_POHTable) results[7];
        Return0 = (BAPIRET2Table) results[8];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_POTH_UPLOAD.  
    /// 
    /// </summary>
    /// <param name="Mblnr"></param>
    /// <param name="Mjahr"></param>
    /// <param name="Returncode"></param>
    /// <param name="Bct10"></param>
    /// <param name="Budat"></param>
    /// <param name="Bwart"></param>
    /// <param name="Ebeln"></param>
    /// <param name="Pt_Kc"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_POTH_UPLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_POTH_UPLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_POTH_UPLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_POTH_UPLOAD.Response")]
    public virtual void Zmm_Rfc_Poth_Upload (

     [RfcParameter(AbapName = "BCT10",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("BCT10", IsNullable=false, Namespace="")]
     string Bct10,
     [RfcParameter(AbapName = "BUDAT",RfcType=RFCTYPE.RFCTYPE_DATE, Optional = true, Direction = RFCINOUT.IN, Length = 8, Length2 = 16)]
     [XmlElement("BUDAT", IsNullable=false, Namespace="")]
     string Budat,
     [RfcParameter(AbapName = "BWART",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 3, Length2 = 6)]
     [XmlElement("BWART", IsNullable=false, Namespace="")]
     string Bwart,
     [RfcParameter(AbapName = "EBELN",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("EBELN", IsNullable=false, Namespace="")]
     string Ebeln,
     [RfcParameter(AbapName = "MBLNR",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 10, Length2 = 20)]
     [XmlElement("MBLNR", IsNullable=false, Namespace="")]
     out string Mblnr,
     [RfcParameter(AbapName = "MJAHR",RfcType=RFCTYPE.RFCTYPE_NUM, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 8)]
     [XmlElement("MJAHR", IsNullable=false, Namespace="")]
     out string Mjahr,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "PT_KC",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("PT_--5fKC", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_RCUPTable Pt_Kc,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Poth_Upload",new object[] {
                            Bct10,Budat,Bwart,Ebeln,Pt_Kc,Return0 });
        Mblnr = (string) results[0];
        Mjahr = (string) results[1];
        Returncode = (string) results[2];
        Pt_Kc = (ZSMM_RFC_RCUPTable) results[3];
        Return0 = (BAPIRET2Table) results[4];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_BGY_DOWNLOAD.  
    /// 
    /// </summary>
    /// <param name="Returncode"></param>
    /// <param name="Name"></param>
    /// <param name="P_Getail"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_BGY_DOWNLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_BGY_DOWNLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_BGY_DOWNLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_BGY_DOWNLOAD.Response")]
    public virtual void Zmm_Rfc_Bgy_Download (

     [RfcParameter(AbapName = "NAME",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("NAME", IsNullable=false, Namespace="")]
     string Name,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "P_GETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("P_--5fGETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_BGYTable P_Getail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Bgy_Download",new object[] {
                            Name,P_Getail,Return0 });
        Returncode = (string) results[0];
        P_Getail = (ZSMM_RFC_BGYTable) results[1];
        Return0 = (BAPIRET2Table) results[2];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_BF_UPLOAD.  
    /// 
    /// </summary>
    /// <param name="Mblnr"></param>
    /// <param name="Mjahr"></param>
    /// <param name="Returncode"></param>
    /// <param name="Aedat"></param>
    /// <param name="Bct10"></param>
    /// <param name="Bwart"></param>
    /// <param name="Rsnum"></param>
    /// <param name="Werks"></param>
    /// <param name="G_Detail"></param>
    /// <param name="P_Detail"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_BF_UPLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_BF_UPLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_BF_UPLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_BF_UPLOAD.Response")]
    public virtual void Zmm_Rfc_Bf_Upload (

     [RfcParameter(AbapName = "AEDAT",RfcType=RFCTYPE.RFCTYPE_DATE, Optional = false, Direction = RFCINOUT.IN, Length = 8, Length2 = 16)]
     [XmlElement("AEDAT", IsNullable=false, Namespace="")]
     string Aedat,
     [RfcParameter(AbapName = "BCT10",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("BCT10", IsNullable=false, Namespace="")]
     string Bct10,
     [RfcParameter(AbapName = "BWART",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 3, Length2 = 6)]
     [XmlElement("BWART", IsNullable=false, Namespace="")]
     string Bwart,
     [RfcParameter(AbapName = "RSNUM",RfcType=RFCTYPE.RFCTYPE_NUM, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("RSNUM", IsNullable=false, Namespace="")]
     string Rsnum,
     [RfcParameter(AbapName = "WERKS",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 4, Length2 = 8)]
     [XmlElement("WERKS", IsNullable=false, Namespace="")]
     string Werks,
     [RfcParameter(AbapName = "MBLNR",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 10, Length2 = 20)]
     [XmlElement("MBLNR", IsNullable=false, Namespace="")]
     out string Mblnr,
     [RfcParameter(AbapName = "MJAHR",RfcType=RFCTYPE.RFCTYPE_NUM, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 8)]
     [XmlElement("MJAHR", IsNullable=false, Namespace="")]
     out string Mjahr,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "G_DETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("G_--5fDETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_RCTPTable G_Detail,
     [RfcParameter(AbapName = "P_DETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("P_--5fDETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_PBATable P_Detail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Bf_Upload",new object[] {
                            Aedat,Bct10,Bwart,Rsnum,Werks,G_Detail,P_Detail,Return0 });
        Mblnr = (string) results[0];
        Mjahr = (string) results[1];
        Returncode = (string) results[2];
        G_Detail = (ZSMM_RFC_RCTPTable) results[3];
        P_Detail = (ZSMM_RFC_PBATable) results[4];
        Return0 = (BAPIRET2Table) results[5];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_HWPCCX_DWNLOAD.  
    /// 
    /// </summary>
    /// <param name="Returncode"></param>
    /// <param name="P_Charg"></param>
    /// <param name="P_Matnr"></param>
    /// <param name="P_Werks"></param>
    /// <param name="It_Output"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_HWPCCX_DWNLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_HWPCCX_DWNLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_HWPCCX_DWNLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_HWPCCX_DWNLOAD.Response")]
    public virtual void Zmm_Rfc_Hwpccx_Dwnload (

     [RfcParameter(AbapName = "P_CHARG",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("P_--5fCHARG", IsNullable=false, Namespace="")]
     string P_Charg,
     [RfcParameter(AbapName = "P_MATNR",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 18, Length2 = 36)]
     [XmlElement("P_--5fMATNR", IsNullable=false, Namespace="")]
     string P_Matnr,
     [RfcParameter(AbapName = "P_WERKS",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 4, Length2 = 8)]
     [XmlElement("P_--5fWERKS", IsNullable=false, Namespace="")]
     string P_Werks,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "IT_OUTPUT",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("IT_--5fOUTPUT", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_HWPCCXTable It_Output,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Hwpccx_Dwnload",new object[] {
                            P_Charg,P_Matnr,P_Werks,It_Output,Return0 });
        Returncode = (string) results[0];
        It_Output = (ZSMM_RFC_HWPCCXTable) results[1];
        Return0 = (BAPIRET2Table) results[2];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_WLPZ_DOWNLOAD.  
    /// 
    /// </summary>
    /// <param name="Returncode"></param>
    /// <param name="Mblnr"></param>
    /// <param name="Mjahr"></param>
    /// <param name="P_Getail"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_WLPZ_DOWNLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_WLPZ_DOWNLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_WLPZ_DOWNLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_WLPZ_DOWNLOAD.Response")]
    public virtual void Zmm_Rfc_Wlpz_Download (

     [RfcParameter(AbapName = "MBLNR",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("MBLNR", IsNullable=false, Namespace="")]
     string Mblnr,
     [RfcParameter(AbapName = "MJAHR",RfcType=RFCTYPE.RFCTYPE_NUM, Optional = false, Direction = RFCINOUT.IN, Length = 4, Length2 = 8)]
     [XmlElement("MJAHR", IsNullable=false, Namespace="")]
     string Mjahr,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "P_GETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("P_--5fGETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_WLPZTable P_Getail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Wlpz_Download",new object[] {
                            Mblnr,Mjahr,P_Getail,Return0 });
        Returncode = (string) results[0];
        P_Getail = (ZSMM_RFC_WLPZTable) results[1];
        Return0 = (BAPIRET2Table) results[2];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_PDSM_DOWNLOAD.  
    /// 
    /// </summary>
    /// <param name="Returncode"></param>
    /// <param name="Iblnr"></param>
    /// <param name="Werks"></param>
    /// <param name="P_Getail"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_PDSM_DOWNLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_PDSM_DOWNLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_PDSM_DOWNLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_PDSM_DOWNLOAD.Response")]
    public virtual void Zmm_Rfc_Pdsm_Download (

     [RfcParameter(AbapName = "IBLNR",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("IBLNR", IsNullable=false, Namespace="")]
     string Iblnr,
     [RfcParameter(AbapName = "WERKS",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 4, Length2 = 8)]
     [XmlElement("WERKS", IsNullable=false, Namespace="")]
     string Werks,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "P_GETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("P_--5fGETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_PDSMTable P_Getail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Pdsm_Download",new object[] {
                            Iblnr,Werks,P_Getail,Return0 });
        Returncode = (string) results[0];
        P_Getail = (ZSMM_RFC_PDSMTable) results[1];
        Return0 = (BAPIRET2Table) results[2];

    }

    /// <summary>
    /// Remote Function Module ZAMM_BFCK_UPLOAD.  
    /// 
    /// </summary>
    /// <param name="Mblnr"></param>
    /// <param name="Mjahr"></param>
    /// <param name="Returncode"></param>
    /// <param name="Bct10"></param>
    /// <param name="Budat"></param>
    /// <param name="Werks"></param>
    /// <param name="P_Detail"></param>
    /// <param name="Return"></param>
    [RfcMethod(AbapName = "ZAMM_BFCK_UPLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZAMM_BFCK_UPLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZAMM_BFCK_UPLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZAMM_BFCK_UPLOAD.Response")]
    public virtual void Zamm_Bfck_Upload (

     [RfcParameter(AbapName = "BCT10",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("BCT10", IsNullable=false, Namespace="")]
     string Bct10,
     [RfcParameter(AbapName = "BUDAT",RfcType=RFCTYPE.RFCTYPE_DATE, Optional = false, Direction = RFCINOUT.IN, Length = 8, Length2 = 16)]
     [XmlElement("BUDAT", IsNullable=false, Namespace="")]
     string Budat,
     [RfcParameter(AbapName = "WERKS",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 4, Length2 = 8)]
     [XmlElement("WERKS", IsNullable=false, Namespace="")]
     string Werks,
     [RfcParameter(AbapName = "MBLNR",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 10, Length2 = 20)]
     [XmlElement("MBLNR", IsNullable=false, Namespace="")]
     out string Mblnr,
     [RfcParameter(AbapName = "MJAHR",RfcType=RFCTYPE.RFCTYPE_NUM, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 8)]
     [XmlElement("MJAHR", IsNullable=false, Namespace="")]
     out string Mjahr,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "P_DETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("P_--5fDETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_BFCKTable P_Detail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return)
    {
        object[]results = null;
        results = this.SAPInvoke("Zamm_Bfck_Upload",new object[] {
                            Bct10,Budat,Werks,P_Detail,Return });
        Mblnr = (string) results[0];
        Mjahr = (string) results[1];
        Returncode = (string) results[2];
        P_Detail = (ZSMM_RFC_BFCKTable) results[3];
        Return = (BAPIRET2Table) results[4];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_BFCK_DOWNLOAD.  
    /// 
    /// </summary>
    /// <param name="Returncode"></param>
    /// <param name="G_Detail"></param>
    /// <param name="P_Getail"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_BFCK_DOWNLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_BFCK_DOWNLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_BFCK_DOWNLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_BFCK_DOWNLOAD.Response")]
    public virtual void Zmm_Rfc_Bfck_Download (

     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "G_DETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("G_--5fDETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_POTTable G_Detail,
     [RfcParameter(AbapName = "P_GETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("P_--5fGETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_POMTable P_Getail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Bfck_Download",new object[] {
                            G_Detail,P_Getail,Return0 });
        Returncode = (string) results[0];
        G_Detail = (ZSMM_RFC_POTTable) results[1];
        P_Getail = (ZSMM_RFC_POMTable) results[2];
        Return0 = (BAPIRET2Table) results[3];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_BFCK_UPLOAD.  
    /// 
    /// </summary>
    /// <param name="Mblnr"></param>
    /// <param name="Mjahr"></param>
    /// <param name="Returncode"></param>
    /// <param name="Bct10"></param>
    /// <param name="Budat"></param>
    /// <param name="Werks"></param>
    /// <param name="P_Detail"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_BFCK_UPLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_BFCK_UPLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_BFCK_UPLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_BFCK_UPLOAD.Response")]
    public virtual void Zmm_Rfc_Bfck_Upload (

     [RfcParameter(AbapName = "BCT10",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("BCT10", IsNullable=false, Namespace="")]
     string Bct10,
     [RfcParameter(AbapName = "BUDAT",RfcType=RFCTYPE.RFCTYPE_DATE, Optional = false, Direction = RFCINOUT.IN, Length = 8, Length2 = 16)]
     [XmlElement("BUDAT", IsNullable=false, Namespace="")]
     string Budat,
     [RfcParameter(AbapName = "WERKS",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 4, Length2 = 8)]
     [XmlElement("WERKS", IsNullable=false, Namespace="")]
     string Werks,
     [RfcParameter(AbapName = "MBLNR",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 10, Length2 = 20)]
     [XmlElement("MBLNR", IsNullable=false, Namespace="")]
     out string Mblnr,
     [RfcParameter(AbapName = "MJAHR",RfcType=RFCTYPE.RFCTYPE_NUM, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 8)]
     [XmlElement("MJAHR", IsNullable=false, Namespace="")]
     out string Mjahr,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "P_DETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("P_--5fDETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_BFCKTable P_Detail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Bfck_Upload",new object[] {
                            Bct10,Budat,Werks,P_Detail,Return0 });
        Mblnr = (string) results[0];
        Mjahr = (string) results[1];
        Returncode = (string) results[2];
        P_Detail = (ZSMM_RFC_BFCKTable) results[3];
        Return0 = (BAPIRET2Table) results[4];

    }

    /// <summary>
    /// Remote Function Module ZMM_RFC_DBQC_DOWNLOAD.  
    /// 
    /// </summary>
    /// <param name="Name1"></param>
    /// <param name="Reswk"></param>
    /// <param name="Returncode"></param>
    /// <param name="Po_Num"></param>
    /// <param name="Po_Detail"></param>
    /// <param name="Return0"></param>
    [RfcMethod(AbapName = "ZMM_RFC_DBQC_DOWNLOAD")]
    [SoapDocumentMethodAttribute("http://tempuri.org/ZMM_RFC_DBQC_DOWNLOAD",
     RequestNamespace = "urn:sap-com:document:sap:rfc:functions",
     RequestElementName = "ZMM_RFC_DBQC_DOWNLOAD",
     ResponseNamespace = "urn:sap-com:document:sap:rfc:functions",
     ResponseElementName = "ZMM_RFC_DBQC_DOWNLOAD.Response")]
    public virtual void Zmm_Rfc_Dbqc_Download (

     [RfcParameter(AbapName = "PO_NUM",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 10, Length2 = 20)]
     [XmlElement("PO_--5fNUM", IsNullable=false, Namespace="")]
     string Po_Num,
     [RfcParameter(AbapName = "NAME1",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 30, Length2 = 60)]
     [XmlElement("NAME1", IsNullable=false, Namespace="")]
     out string Name1,
     [RfcParameter(AbapName = "RESWK",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 4, Length2 = 8)]
     [XmlElement("RESWK", IsNullable=false, Namespace="")]
     out string Reswk,
     [RfcParameter(AbapName = "RETURNCODE",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = true, Direction = RFCINOUT.OUT, Length = 1, Length2 = 2)]
     [XmlElement("RETURNCODE", IsNullable=false, Namespace="")]
     out string Returncode,
     [RfcParameter(AbapName = "PO_DETAIL",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("PO_--5fDETAIL", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref ZSMM_RFC_POSTable Po_Detail,
     [RfcParameter(AbapName = "RETURN",RfcType=RFCTYPE.RFCTYPE_ITAB, Optional = false, Direction = RFCINOUT.INOUT)]
     [XmlArray("RETURN", IsNullable=false, Namespace="")]
     [XmlArrayItem("item", IsNullable=false)]
     ref BAPIRET2Table Return0)
    {
        object[]results = null;
        results = this.SAPInvoke("Zmm_Rfc_Dbqc_Download",new object[] {
                            Po_Num,Po_Detail,Return0 });
        Name1 = (string) results[0];
        Reswk = (string) results[1];
        Returncode = (string) results[2];
        Po_Detail = (ZSMM_RFC_POSTable) results[3];
        Return0 = (BAPIRET2Table) results[4];

    }

  } 

}
