
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2008-08-13
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SapService
{

  /// <summary>
  /// 
  /// </summary>
  [RfcStructure(AbapName ="TAB512" , Length = 512, Length2 = 1024)]
  [Serializable]
  public class TAB512 : SAPStructure
  {
   

    /// <summary>
    /// Character field length 512
    /// </summary>
 
    [RfcField(AbapName = "WA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 512, Length2 = 1024, Offset = 0, Offset2 = 0)]
    [XmlElement("WA")]
    public string Wa
    { 
       get
       {
          return _Wa;
       }
       set
       {
          _Wa = value;
       }
    }
    private string _Wa;

  }

}
