
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 2.0
//     Created at 2008-08-13
//     Created from Windows
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace SapService
{

  /// <summary>
  /// 
  /// </summary>
  [RfcStructure(AbapName ="ZSMM_RFC_PDSM" , Length = 196, Length2 = 362)]
  [Serializable]
  public class ZSMM_RFC_PDSM : SAPStructure
  {
   

    /// <summary>
    /// Physical Inventory Document
    /// </summary>
 
    [RfcField(AbapName = "IBLNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 0, Offset2 = 0)]
    [XmlElement("IBLNR")]
    public string Iblnr
    { 
       get
       {
          return _Iblnr;
       }
       set
       {
          _Iblnr = value;
       }
    }
    private string _Iblnr;


    /// <summary>
    /// Plant
    /// </summary>
 
    [RfcField(AbapName = "WERKS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 10, Offset2 = 20)]
    [XmlElement("WERKS")]
    public string Werks
    { 
       get
       {
          return _Werks;
       }
       set
       {
          _Werks = value;
       }
    }
    private string _Werks;


    /// <summary>
    /// Material Number
    /// </summary>
 
    [RfcField(AbapName = "MATNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Length2 = 36, Offset = 14, Offset2 = 28)]
    [XmlElement("MATNR")]
    public string Matnr
    { 
       get
       {
          return _Matnr;
       }
       set
       {
          _Matnr = value;
       }
    }
    private string _Matnr;


    /// <summary>
    /// Batch Number
    /// </summary>
 
    [RfcField(AbapName = "CHARG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 32, Offset2 = 64)]
    [XmlElement("CHARG")]
    public string Charg
    { 
       get
       {
          return _Charg;
       }
       set
       {
          _Charg = value;
       }
    }
    private string _Charg;


    /// <summary>
    /// Storage location
    /// </summary>
 
    [RfcField(AbapName = "LGORT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Length2 = 8, Offset = 42, Offset2 = 84)]
    [XmlElement("LGORT")]
    public string Lgort
    { 
       get
       {
          return _Lgort;
       }
       set
       {
          _Lgort = value;
       }
    }
    private string _Lgort;


    /// <summary>
    /// Material description
    /// </summary>
 
    [RfcField(AbapName = "MAKTX", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Length2 = 80, Offset = 46, Offset2 = 92)]
    [XmlElement("MAKTX")]
    public string Maktx
    { 
       get
       {
          return _Maktx;
       }
       set
       {
          _Maktx = value;
       }
    }
    private string _Maktx;


    /// <summary>
    /// Base Unit of Measure
    /// </summary>
 
    [RfcField(AbapName = "MEINS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Length2 = 6, Offset = 86, Offset2 = 172)]
    [XmlElement("MEINS")]
    public string Meins
    { 
       get
       {
          return _Meins;
       }
       set
       {
          _Meins = value;
       }
    }
    private string _Meins;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "ZLDAT", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Length2 = 16, Offset = 89, Offset2 = 178)]
    [XmlElement("ZLDAT")]
    public string Zldat
    { 
       get
       {
          return _Zldat;
       }
       set
       {
          _Zldat = value;
       }
    }
    private string _Zldat;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "ZDQKC", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 97, Offset2 = 194)]
    [XmlElement("ZDQKC")]
    public Decimal Zdqkc
    { 
       get
       {
          return _Zdqkc;
       }
       set
       {
          _Zdqkc = value;
       }
    }
    private Decimal _Zdqkc;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "BGYDM", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 104, Offset2 = 202)]
    [XmlElement("BGYDM")]
    public string Bgydm
    { 
       get
       {
          return _Bgydm;
       }
       set
       {
          _Bgydm = value;
       }
    }
    private string _Bgydm;


    /// <summary>
    /// Moving Average Price/Periodic Unit Price
    /// </summary>
 
    [RfcField(AbapName = "VERPR", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 6, Length2 = 6, Decimals = 2, Offset = 114, Offset2 = 222)]
    [XmlElement("VERPR")]
    public Decimal Verpr
    { 
       get
       {
          return _Verpr;
       }
       set
       {
          _Verpr = value;
       }
    }
    private Decimal _Verpr;


    /// <summary>
    /// Char 15
    /// </summary>
 
    [RfcField(AbapName = "BCT50", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 120, Offset2 = 228)]
    [XmlElement("BCT50")]
    public string Bct50
    { 
       get
       {
          return _Bct50;
       }
       set
       {
          _Bct50 = value;
       }
    }
    private string _Bct50;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "BCT51", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 135, Offset2 = 258)]
    [XmlElement("BCT51")]
    public Decimal Bct51
    { 
       get
       {
          return _Bct51;
       }
       set
       {
          _Bct51 = value;
       }
    }
    private Decimal _Bct51;


    /// <summary>
    /// Char 15
    /// </summary>
 
    [RfcField(AbapName = "BCT60", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 142, Offset2 = 266)]
    [XmlElement("BCT60")]
    public string Bct60
    { 
       get
       {
          return _Bct60;
       }
       set
       {
          _Bct60 = value;
       }
    }
    private string _Bct60;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "BCT61", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 157, Offset2 = 296)]
    [XmlElement("BCT61")]
    public Decimal Bct61
    { 
       get
       {
          return _Bct61;
       }
       set
       {
          _Bct61 = value;
       }
    }
    private Decimal _Bct61;


    /// <summary>
    /// Char 15
    /// </summary>
 
    [RfcField(AbapName = "BCT70", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Length2 = 30, Offset = 164, Offset2 = 304)]
    [XmlElement("BCT70")]
    public string Bct70
    { 
       get
       {
          return _Bct70;
       }
       set
       {
          _Bct70 = value;
       }
    }
    private string _Bct70;


    /// <summary>
    /// Quantity
    /// </summary>
 
    [RfcField(AbapName = "BCT71", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Length2 = 7, Decimals = 3, Offset = 179, Offset2 = 334)]
    [XmlElement("BCT71")]
    public Decimal Bct71
    { 
       get
       {
          return _Bct71;
       }
       set
       {
          _Bct71 = value;
       }
    }
    private Decimal _Bct71;


    /// <summary>
    /// 
    /// </summary>
 
    [RfcField(AbapName = "BCT20", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Length2 = 20, Offset = 186, Offset2 = 342)]
    [XmlElement("BCT20")]
    public string Bct20
    { 
       get
       {
          return _Bct20;
       }
       set
       {
          _Bct20 = value;
       }
    }
    private string _Bct20;

  }

}
