//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace RFSystem.rfid2021Service
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="rfidServiceSoap", Namespace="http://tempuri.org/")]
    public partial class rfidService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sendMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendMsgNotOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInvPhysicOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBxUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback currDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPrintOperationCompleted;
        
        private System.Threading.SendOrPostCallback getWarehouseOperationCompleted;
        
        private System.Threading.SendOrPostCallback getShiperReceiverOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public rfidService() {
            this.Url = global::RFSystem.Properties.Settings.Default.RFSystem_rfid2021_rfidService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sendMsgCompletedEventHandler sendMsgCompleted;
        
        /// <remarks/>
        public event sendMsgNotOutCompletedEventHandler sendMsgNotOutCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event getInvPhysicCompletedEventHandler getInvPhysicCompleted;
        
        /// <remarks/>
        public event getBxUsersCompletedEventHandler getBxUsersCompleted;
        
        /// <remarks/>
        public event currDateCompletedEventHandler currDateCompleted;
        
        /// <remarks/>
        public event getPrintCompletedEventHandler getPrintCompleted;
        
        /// <remarks/>
        public event getWarehouseCompletedEventHandler getWarehouseCompleted;
        
        /// <remarks/>
        public event getShiperReceiverCompletedEventHandler getShiperReceiverCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sendMsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessagePack sendMsg(string _serviceid, string _BxUserID, string _BxUserName, string _BxJobID, System.Data.DataSet _inDs, out System.Data.DataSet _outDs) {
            object[] results = this.Invoke("sendMsg", new object[] {
                        _serviceid,
                        _BxUserID,
                        _BxUserName,
                        _BxJobID,
                        _inDs});
            _outDs = ((System.Data.DataSet)(results[1]));
            return ((MessagePack)(results[0]));
        }
        
        /// <remarks/>
        public void sendMsgAsync(string _serviceid, string _BxUserID, string _BxUserName, string _BxJobID, System.Data.DataSet _inDs) {
            this.sendMsgAsync(_serviceid, _BxUserID, _BxUserName, _BxJobID, _inDs, null);
        }
        
        /// <remarks/>
        public void sendMsgAsync(string _serviceid, string _BxUserID, string _BxUserName, string _BxJobID, System.Data.DataSet _inDs, object userState) {
            if ((this.sendMsgOperationCompleted == null)) {
                this.sendMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendMsgOperationCompleted);
            }
            this.InvokeAsync("sendMsg", new object[] {
                        _serviceid,
                        _BxUserID,
                        _BxUserName,
                        _BxJobID,
                        _inDs}, this.sendMsgOperationCompleted, userState);
        }
        
        private void OnsendMsgOperationCompleted(object arg) {
            if ((this.sendMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendMsgCompleted(this, new sendMsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sendMsgNotOut", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessagePack sendMsgNotOut(string _serviceid, string _BxUserID, string _BxUserName, string _BxJobID, System.Data.DataSet _inDs) {
            object[] results = this.Invoke("sendMsgNotOut", new object[] {
                        _serviceid,
                        _BxUserID,
                        _BxUserName,
                        _BxJobID,
                        _inDs});
            return ((MessagePack)(results[0]));
        }
        
        /// <remarks/>
        public void sendMsgNotOutAsync(string _serviceid, string _BxUserID, string _BxUserName, string _BxJobID, System.Data.DataSet _inDs) {
            this.sendMsgNotOutAsync(_serviceid, _BxUserID, _BxUserName, _BxJobID, _inDs, null);
        }
        
        /// <remarks/>
        public void sendMsgNotOutAsync(string _serviceid, string _BxUserID, string _BxUserName, string _BxJobID, System.Data.DataSet _inDs, object userState) {
            if ((this.sendMsgNotOutOperationCompleted == null)) {
                this.sendMsgNotOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendMsgNotOutOperationCompleted);
            }
            this.InvokeAsync("sendMsgNotOut", new object[] {
                        _serviceid,
                        _BxUserID,
                        _BxUserName,
                        _BxJobID,
                        _inDs}, this.sendMsgNotOutOperationCompleted, userState);
        }
        
        private void OnsendMsgNotOutOperationCompleted(object arg) {
            if ((this.sendMsgNotOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendMsgNotOutCompleted(this, new sendMsgNotOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessagePack Login(string _username, string _password, out string BxUserID, out string BxUserName, out string BxJobId, out privilidge PrivateStr, out string DbConnStr) {
            object[] results = this.Invoke("Login", new object[] {
                        _username,
                        _password});
            BxUserID = ((string)(results[1]));
            BxUserName = ((string)(results[2]));
            BxJobId = ((string)(results[3]));
            PrivateStr = ((privilidge)(results[4]));
            DbConnStr = ((string)(results[5]));
            return ((MessagePack)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string _username, string _password) {
            this.LoginAsync(_username, _password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string _username, string _password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        _username,
                        _password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInvPhysic", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessagePack getInvPhysic(out System.Data.DataSet _outDs) {
            object[] results = this.Invoke("getInvPhysic", new object[0]);
            _outDs = ((System.Data.DataSet)(results[1]));
            return ((MessagePack)(results[0]));
        }
        
        /// <remarks/>
        public void getInvPhysicAsync() {
            this.getInvPhysicAsync(null);
        }
        
        /// <remarks/>
        public void getInvPhysicAsync(object userState) {
            if ((this.getInvPhysicOperationCompleted == null)) {
                this.getInvPhysicOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInvPhysicOperationCompleted);
            }
            this.InvokeAsync("getInvPhysic", new object[0], this.getInvPhysicOperationCompleted, userState);
        }
        
        private void OngetInvPhysicOperationCompleted(object arg) {
            if ((this.getInvPhysicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInvPhysicCompleted(this, new getInvPhysicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getBxUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessagePack getBxUsers(out System.Data.DataSet _outDs) {
            object[] results = this.Invoke("getBxUsers", new object[0]);
            _outDs = ((System.Data.DataSet)(results[1]));
            return ((MessagePack)(results[0]));
        }
        
        /// <remarks/>
        public void getBxUsersAsync() {
            this.getBxUsersAsync(null);
        }
        
        /// <remarks/>
        public void getBxUsersAsync(object userState) {
            if ((this.getBxUsersOperationCompleted == null)) {
                this.getBxUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBxUsersOperationCompleted);
            }
            this.InvokeAsync("getBxUsers", new object[0], this.getBxUsersOperationCompleted, userState);
        }
        
        private void OngetBxUsersOperationCompleted(object arg) {
            if ((this.getBxUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBxUsersCompleted(this, new getBxUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/currDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime currDate() {
            object[] results = this.Invoke("currDate", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void currDateAsync() {
            this.currDateAsync(null);
        }
        
        /// <remarks/>
        public void currDateAsync(object userState) {
            if ((this.currDateOperationCompleted == null)) {
                this.currDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OncurrDateOperationCompleted);
            }
            this.InvokeAsync("currDate", new object[0], this.currDateOperationCompleted, userState);
        }
        
        private void OncurrDateOperationCompleted(object arg) {
            if ((this.currDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.currDateCompleted(this, new currDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPrint", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessagePack getPrint(out System.Data.DataSet _outDs) {
            object[] results = this.Invoke("getPrint", new object[0]);
            _outDs = ((System.Data.DataSet)(results[1]));
            return ((MessagePack)(results[0]));
        }
        
        /// <remarks/>
        public void getPrintAsync() {
            this.getPrintAsync(null);
        }
        
        /// <remarks/>
        public void getPrintAsync(object userState) {
            if ((this.getPrintOperationCompleted == null)) {
                this.getPrintOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPrintOperationCompleted);
            }
            this.InvokeAsync("getPrint", new object[0], this.getPrintOperationCompleted, userState);
        }
        
        private void OngetPrintOperationCompleted(object arg) {
            if ((this.getPrintCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPrintCompleted(this, new getPrintCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getWarehouse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessagePack getWarehouse(out System.Data.DataSet _outDs) {
            object[] results = this.Invoke("getWarehouse", new object[0]);
            _outDs = ((System.Data.DataSet)(results[1]));
            return ((MessagePack)(results[0]));
        }
        
        /// <remarks/>
        public void getWarehouseAsync() {
            this.getWarehouseAsync(null);
        }
        
        /// <remarks/>
        public void getWarehouseAsync(object userState) {
            if ((this.getWarehouseOperationCompleted == null)) {
                this.getWarehouseOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetWarehouseOperationCompleted);
            }
            this.InvokeAsync("getWarehouse", new object[0], this.getWarehouseOperationCompleted, userState);
        }
        
        private void OngetWarehouseOperationCompleted(object arg) {
            if ((this.getWarehouseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getWarehouseCompleted(this, new getWarehouseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getShiperReceiver", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MessagePack getShiperReceiver(out System.Data.DataSet _outDs) {
            object[] results = this.Invoke("getShiperReceiver", new object[0]);
            _outDs = ((System.Data.DataSet)(results[1]));
            return ((MessagePack)(results[0]));
        }
        
        /// <remarks/>
        public void getShiperReceiverAsync() {
            this.getShiperReceiverAsync(null);
        }
        
        /// <remarks/>
        public void getShiperReceiverAsync(object userState) {
            if ((this.getShiperReceiverOperationCompleted == null)) {
                this.getShiperReceiverOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetShiperReceiverOperationCompleted);
            }
            this.InvokeAsync("getShiperReceiver", new object[0], this.getShiperReceiverOperationCompleted, userState);
        }
        
        private void OngetShiperReceiverOperationCompleted(object arg) {
            if ((this.getShiperReceiverCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getShiperReceiverCompleted(this, new getShiperReceiverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessagePack {
        
        private int codeField;
        
        private string messageField;
        
        private object contentField;
        
        private bool resultField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public object Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class privilidge {
        
        private string printBinField;
        
        private string printLabelField;
        
        private string cGSHField;
        
        private string cGRKField;
        
        private string dGRKField;
        
        private string yCRKField;
        
        private string pANDIANField;
        
        private string ykField;
        
        private string sCLLField;
        
        private string bfField;
        
        private string thField;
        
        private string cxField;
        
        private string dGCKField;
        
        private string sjField;
        
        private string dBGCKField;
        
        private string bYDField;
        
        private string hWCXField;
        
        private string pCCXField;
        
        private string kCTHField;
        
        private string dJKTHField;
        
        private bool isAdminField;
        
        private System.DateTime serverTimeField;
        
        /// <remarks/>
        public string PrintBin {
            get {
                return this.printBinField;
            }
            set {
                this.printBinField = value;
            }
        }
        
        /// <remarks/>
        public string PrintLabel {
            get {
                return this.printLabelField;
            }
            set {
                this.printLabelField = value;
            }
        }
        
        /// <remarks/>
        public string CGSH {
            get {
                return this.cGSHField;
            }
            set {
                this.cGSHField = value;
            }
        }
        
        /// <remarks/>
        public string CGRK {
            get {
                return this.cGRKField;
            }
            set {
                this.cGRKField = value;
            }
        }
        
        /// <remarks/>
        public string DGRK {
            get {
                return this.dGRKField;
            }
            set {
                this.dGRKField = value;
            }
        }
        
        /// <remarks/>
        public string YCRK {
            get {
                return this.yCRKField;
            }
            set {
                this.yCRKField = value;
            }
        }
        
        /// <remarks/>
        public string PANDIAN {
            get {
                return this.pANDIANField;
            }
            set {
                this.pANDIANField = value;
            }
        }
        
        /// <remarks/>
        public string YK {
            get {
                return this.ykField;
            }
            set {
                this.ykField = value;
            }
        }
        
        /// <remarks/>
        public string SCLL {
            get {
                return this.sCLLField;
            }
            set {
                this.sCLLField = value;
            }
        }
        
        /// <remarks/>
        public string BF {
            get {
                return this.bfField;
            }
            set {
                this.bfField = value;
            }
        }
        
        /// <remarks/>
        public string TH {
            get {
                return this.thField;
            }
            set {
                this.thField = value;
            }
        }
        
        /// <remarks/>
        public string CX {
            get {
                return this.cxField;
            }
            set {
                this.cxField = value;
            }
        }
        
        /// <remarks/>
        public string DGCK {
            get {
                return this.dGCKField;
            }
            set {
                this.dGCKField = value;
            }
        }
        
        /// <remarks/>
        public string SJ {
            get {
                return this.sjField;
            }
            set {
                this.sjField = value;
            }
        }
        
        /// <remarks/>
        public string DBGCK {
            get {
                return this.dBGCKField;
            }
            set {
                this.dBGCKField = value;
            }
        }
        
        /// <remarks/>
        public string BYD {
            get {
                return this.bYDField;
            }
            set {
                this.bYDField = value;
            }
        }
        
        /// <remarks/>
        public string HWCX {
            get {
                return this.hWCXField;
            }
            set {
                this.hWCXField = value;
            }
        }
        
        /// <remarks/>
        public string PCCX {
            get {
                return this.pCCXField;
            }
            set {
                this.pCCXField = value;
            }
        }
        
        /// <remarks/>
        public string KCTH {
            get {
                return this.kCTHField;
            }
            set {
                this.kCTHField = value;
            }
        }
        
        /// <remarks/>
        public string DJKTH {
            get {
                return this.dJKTHField;
            }
            set {
                this.dJKTHField = value;
            }
        }
        
        /// <remarks/>
        public bool isAdmin {
            get {
                return this.isAdminField;
            }
            set {
                this.isAdminField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ServerTime {
            get {
                return this.serverTimeField;
            }
            set {
                this.serverTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void sendMsgCompletedEventHandler(object sender, sendMsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessagePack Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessagePack)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet _outDs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void sendMsgNotOutCompletedEventHandler(object sender, sendMsgNotOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendMsgNotOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendMsgNotOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessagePack Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessagePack)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessagePack Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessagePack)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string BxUserID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string BxUserName {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string BxJobId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public privilidge PrivateStr {
            get {
                this.RaiseExceptionIfNecessary();
                return ((privilidge)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string DbConnStr {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getInvPhysicCompletedEventHandler(object sender, getInvPhysicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInvPhysicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInvPhysicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessagePack Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessagePack)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet _outDs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getBxUsersCompletedEventHandler(object sender, getBxUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBxUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBxUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessagePack Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessagePack)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet _outDs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void currDateCompletedEventHandler(object sender, currDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class currDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal currDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getPrintCompletedEventHandler(object sender, getPrintCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPrintCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPrintCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessagePack Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessagePack)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet _outDs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getWarehouseCompletedEventHandler(object sender, getWarehouseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getWarehouseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getWarehouseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessagePack Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessagePack)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet _outDs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getShiperReceiverCompletedEventHandler(object sender, getShiperReceiverCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getShiperReceiverCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getShiperReceiverCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MessagePack Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MessagePack)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet _outDs {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591